[parity]

chain = "happyshare-spec.json"
base_path = "/data/parity_hs"

[network]
port = 30306
warp = false

[rpc]
port=8547
disable = false
interface = "local"
cors = "all"
apis = ["web3", "personal", "eth", "net","parity","parity_set", "traces", "rpc", "secretstore","signer","parity_accounts"]
hosts = ["none"]

[ipc]
disable = false
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore","signer"]

[websockets]
disable = false
port = 8456
origins = ["all"]  
hosts = ["all"] 

[ui]
disable = false
port = 8180


[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 500
cache_size_db = 64
cache_size_blocks = 8
cache_size_queue = 50
cache_size_state = 25
cache_size = 128 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "on"
scale_verifiers = true
num_verifiers = 6
